# Generated by Django 4.1 on 2022-11-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restaurante_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='estrellas',
            field=models.IntegerField(default=0),
        ),
    ]
