# Generated by Django 4.1 on 2022-11-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_detalleorden_estadoorden_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='subTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadoorden',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
