# Generated by Django 4.1 on 2022-11-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_detalleorden_precio_detalleorden_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='Restaurante',
        ),
        migrations.AddField(
            model_name='orden',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
